// <auto-generated />
using System;
using AlmacenTaller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmacenTaller.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010002808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmacenTaller.Models.InventoryBalance", b =>
                {
                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<int>("OnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("on_hand");

                    b.Property<int>("Reserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PartId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("inventory_balances", (string)null);

                    b.HasData(
                        new
                        {
                            PartId = 1L,
                            LocationId = 100L,
                            OnHand = 8,
                            Reserved = 6,
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PartId = 2L,
                            LocationId = 100L,
                            OnHand = 2,
                            Reserved = 2,
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PartId = 3L,
                            LocationId = 100L,
                            OnHand = 1,
                            Reserved = 3,
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AlmacenTaller.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWorkbench")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_workbench");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("LocationId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = 100L,
                            Active = true,
                            Code = "ALM-PRINCIPAL",
                            CreatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWorkbench = false,
                            Name = "Almacén Central"
                        });
                });

            modelBuilder.Entity("AlmacenTaller.Models.Part", b =>
                {
                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("PartGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_group");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("sku");

                    b.Property<string>("Subgroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subgroup");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PartId");

                    b.ToTable("parts", (string)null);

                    b.HasData(
                        new
                        {
                            PartId = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Family = "Husillos CNC",
                            Name = "Rodamiento Cerámico Híbrido 7008-C",
                            PartGroup = "Mecánico",
                            Sku = "BAL-7008C",
                            Subgroup = "Rodamientos",
                            Unit = "pz",
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PartId = 2L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Family = "Sellado",
                            Name = "Sello Laberíntico Viton 45mm",
                            PartGroup = "Mecánico",
                            Sku = "SEL-VT45",
                            Subgroup = "Sellos",
                            Unit = "pz",
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PartId = 3L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Family = "Instrumentación",
                            Name = "Sensor Térmico PT100 Calibrado",
                            PartGroup = "Eléctrico",
                            Sku = "TH-PT100",
                            Subgroup = "Sensores",
                            Unit = "pz",
                            UpdatedAt = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AlmacenTaller.Models.InventoryBalance", b =>
                {
                    b.HasOne("AlmacenTaller.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenTaller.Models.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
