// <auto-generated />
using AlmacenTaller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmacenTaller.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmacenTaller.Models.Pieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reservado")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockFisico")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("TiempoReposicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Piezas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Husillos CNC",
                            Nombre = "Rodamiento Cerámico Híbrido 7008-C",
                            Reservado = 6,
                            Sku = "BAL-7008C",
                            StockFisico = 8,
                            StockMinimo = 4,
                            TiempoReposicion = "3 semanas"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Sellado",
                            Nombre = "Sello Laberíntico Viton 45mm",
                            Reservado = 2,
                            Sku = "SEL-VT45",
                            StockFisico = 2,
                            StockMinimo = 3,
                            TiempoReposicion = "5 días"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Instrumentación",
                            Nombre = "Sensor Térmico PT100 Calibrado",
                            Reservado = 3,
                            Sku = "TH-PT100",
                            StockFisico = 1,
                            StockMinimo = 2,
                            TiempoReposicion = "12 días"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
